#!/usr/bin/env bash
set -euo pipefail

dir=$(dirname "$0")

declare -a args

nextArgIsPkg=
name=unnamed

for arg in "$@"; do
    if [ "$arg" == "--no-ccache" ]; then
        noCCache=1
        continue
    fi

    # all arguments other than --no-ccache are passed through.
    args+=("$arg")

    if [ -n "$nextArgIsPkg" ]; then
        name="$arg"
        nextArgIsPkg=
        continue
    fi

    if [ "$arg" == "-A" ]; then
        nextArgIsPkg=1
    fi
done

buildDir="/tmp/nds-build-$name"
if [ -d "$buildDir" ]; then
    # TODO: maybe handle this instead of always wiping
    # echo "Reusing existing build directory '$buildDir'. Run 'nd-reset' to wipe it and start the build from scratch."
    echo "Wiping already existing build directory '$buildDir'."
    rm -rf "$buildDir"
else
    echo "Creating new build directory '$buildDir'."
fi
mkdir -p "$buildDir"

#echo "noCCache: $noCCache, pkg: $pkg, args: ${args[@]}"
nix-shell --command "cd $buildDir; source $dir/env.sh; return" "${args[@]}"
